version: "3"
services:
  client:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
    - ./frontend:/usr/local/app/
    - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/
    ports:
    - 80:80
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
    - 7000:7000
    volumes: 
    - ./server:/usr/local/app/