version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
        # entrypoint: /bin/bash
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Start container and verify it's working
          command: |
            docker-compose -f docker-compose.yml up --build -d
            docker ps -a
      # docker tag

  
workflows:
  node-tests:
    jobs:
    - build
    - aws-ecr/build-and-push-image:
        repo: docker_images #ecr repository name
        account-url: AWS_ECR_ACCOUNT_URL
        dockerfile: frontend/Dockerfile
        path: ./frontend
        tag: "v0.1.${CIRCLE_BUILD_NUM}"
        requires:
          - build
      