version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build:
    docker:
      - image: amazon/aws-cli
        # entrypoint: /bin/bash
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
          
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Clear docker volumes
          command: |
            docker volume rm $(docker volume ls -q)

      - run:
          name: Start container and verify it's working
          command: |
            docker-compose -f docker-compose.yml up --build -d
  
workflows:
  node-tests:
    jobs:
    - build
    - aws-ecr/build-and-push-image:
        repo: docker_images #ecr repository name
        tag: "v0.1.${CIRCLE_BUILD_NUM}"
        requires:
          - build
      